from instaclient import InstaClient
from instaclient.errors import *
from database import DataBase

client = InstaClient(driver_path='./chromedriver')

# Login
try:
    client.login(username='themain.end', password='L!iykMt!buJd229V15IC68EMU5CsU$vEzKsLOzxu@BUCiEqI4b7')
except VerificationCodeNecessary:
    code = input('Enter the 2FA security code generated by your Authenticator App or sent to you by SMS')
    client.input_verification_code(code)
except SuspisciousLoginAttemptError as error:
    if error.mode == SuspisciousLoginAttemptError.EMAIL:
        code = input('Enter the security code that was sent to you via email: ')
    else:
        code = input('Enter the security code that was sent to you via SMS: ')
    client.input_security_code(code)

# Menu
print(f"{DataBase.sentCount()}/{DataBase.Count()} Users\n")
print("1- Send")
print("2- Fetch")
choice = int(input('Choose by number: '))

if choice == 1:
	...
elif choice == 2:
	followers = client.get_followers(user=input("Username: "), count=50)
	for follower in followers:
		print(follower['username'])